### ISSUE TITLE
Conflicting build info about host port

### ISSUE THREAD

**Issue by Pastitas** [okyeron/umbrellas#6]
In the docs it's mentioned that only corner pins (A0, A6, 5V, A7) and GND should be connected.
>  QTPy should go on the bottom (picture side) of the umbrellas bottom pcb (the small one) - so the USB jack is in line with the umbrellas pcb. Note - you only need to solder the "corner" pin positions plus the ground pin.

But in the build video the extra pin that gets soldered is A1, not GND. It seems if A1 and GND are both soldered the board does not start up correctly and will only show up on the host as umbrellas host port if connected before powering umbrellas.

When I connect the host cable to the QtPy before powering the pi then it seems to work properly.

Is this something that makes sense or might there be other issues in my kit?

**Comment by Pastitas** [comment]
After changing to a new QtPy things are working, but still I had to de-
solder the thing and the instructions are a bit misleading.

**Comment by okyeron** [comment]
double checking the video now...

OK - so remember the QTpy is upside down in the video - viewing from the bottom. So I'm soldering GND there, not A1.

Do I need to add a picture to the Build doc to show the correct orientation and the pins to solder?

Or what else can be clarified?

Your comment about A1 + GND is interesting tho - there is a bug I'm chasing with regards to the qtpy not booting properly when you plug into USB.

The solution for the moment for this is to just hit the QTPy reset button to reboot it - and then it will come up normally.

**Comment by Pastitas** [comment]
> Do I need to add a picture to the Build doc to show the correct orientation and the pins to solder?

I think it might help.

> OK - so remember the QTpy is upside down in the video - viewing from the bottom. So I'm soldering GND there, not A1.

Precisely, if you flip the board the two pins on the right  closer to the usb c port are A0 and A1. 
![image](https://user-images.githubusercontent.com/10663022/188248509-099e7c9d-8123-45ca-b354-d6c8b102e94d.png)
you can see it here, flip that to the right (putting the usb-port side to the table and pointing up)  and what you get is A0 and A1 on the right, and 5v and GND on the left side.
Unless the video is mirrored in some way, I still think this might be causing issues.

**Comment by v0idkr4ft** [comment]
Pastitas is correct, it is A1 getting soldered in the video, not GND. so is there a correct way to do this?

**Comment by okyeron** [comment]
I've updated the build guide with a picture for position.

Does this help?

https://github.com/okyeron/umbrellas/blob/main/BUILD.md

EDIT - ADDED ARROWS TO PICTURE INDICATE WHERE TO SOLDER.

**Comment by v0idkr4ft** [comment]
Yes, that clarifies. thanks.

**Comment by v0idkr4ft** [comment]
Just a note, neither of the uf2 files worked for my qtpy, thought maybe had a hardware issue, but circuitpython loaded fine, then I compiled your .ino in arduino IDE after setting up requisites and adding elapsedMillis library. code compiled fine and uploaded to qtpy and everything seems to be working, thanks!

**Comment by Pastitas** [comment]
This seems fixed, thanks @v0idkr4ft  and @okyeron for looking into it
